# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Login
  As a user
  I want to have a login process with sign in and sign up options

  Scenario: Navigate to Sign up
    Given a user
    When the user tap 'Sign Up' button
    Then the page 'Sign Up' is opened

  Scenario: Navigate to Sign in
    Given a user
    When the user tap 'Sign In' button
    Then the page 'Sign In' is opened
