# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Login
  As a user
  I want to have a login process with sign in and sign up options

  Scenario: Sign up - Error
    Given a user in 'Sign Up' page
    When the user tap 'Send' button
    Then the alert 'SignUp_Error' is opened

  Scenario: Sign up - OK
    Given a user in 'Sign Up' page
    When the user write the email in 'Email_Textfield'
    And the user tap 'Send' button
    Then the page 'Sign Up' disappear

  Scenario: Navigate to Sign up
    Given a user
    When the user tap 'Sign Up' button
    Then the page 'Sign Up' is opened

  Scenario: Navigate to Sign in
    Given a user
    When the user tap 'Sign In' button
    Then the page 'Sign In' is opened
